name: build-soda
on:
  push:
    branches:
      - 'soda'
  workflow_dispatch:
env:
  WINE_VERSION: 9.0
  BRANCH: experimental_9.0
  REVISION: 0
jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v4

      - name: setup
        working-directory: /home/runner/work/
        run: |
          mkdir -p /home/runner/.config/frogminer/
          sudo apt purge -y ubuntu-advantage-tools python3-update-manager
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'

      - name: clone wine-tkg-git repo and configure
        working-directory: /home/runner/work/
        run: |
          git clone https://github.com/Frogging-Family/wine-tkg-git.git
          cd wine-tkg-git/wine-tkg-git
          sed -i "s/_LOCAL_PRESET=\"\"/_plain_version=\"valve-exp-bleeding\"/g" customization.cfg
          curl https://raw.githubusercontent.com/xioren/build-tools/main/runners/vaniglia/wine-tkg-valve.cfg > wine-tkg-valve.cfg
          cat wine-tkg-valve.cfg >> wine-tkg-profiles/wine-tkg-valve-exp-bleeding.cfg
  
      - name: start build
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/
        run: yes|./non-makepkg-build.sh

      - name: package
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/non-makepkg-builds/
        run: |
          mv wine-tkg-* soda-$WINE_VERSION-$REVISION-x86_64
          tar cJvf soda-$WINE_VERSION-$REVISION-x86_64.tar.xz soda-$WINE_VERSION-$REVISION-x86_64
          mv soda-$WINE_VERSION-$REVISION-x86_64.tar.xz /tmp/soda-$WINE_VERSION-$REVISION-x86_64.tar.xz

      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: "soda-${{ env.WINE_VERSION }}-${{ env.REVISION }}"
          title: "Soda ${{ env.WINE_VERSION }}-${{ env.REVISION }}"
          files: "/tmp/soda-${{ env.WINE_VERSION }}-${{ env.REVISION }}-x86_64.tar.xz"
